In [2]:
import numpy as np

In [33]:
cols = 17
rows = 17

#arena_x, arena_y = np.linspace(0,cols-1,cols), np.linspace(0,rows-1,rows)
arena_x, arena_y = list(range(cols)), list(range(rows))
arena_xv, arena_yv = np.meshgrid(arena_x,arena_y)
#new_arena = np.meshgrid(arena_x,arena_y)
new_arena = zip(*[arena_xv,arena_yv])
#print(list(new_arena))
print(arena_xv)
print(arena_yv)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  

In [14]:
?zip

In [23]:
list(range(17))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [34]:
a = np.ones((3,3))
a[[[0,1],[0,1]],[[0,0],[1,1]]] = 0
a

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.]])

In [35]:
cols = 2
rows = 2

#arena_x, arena_y = np.linspace(0,cols-1,cols), np.linspace(0,rows-1,rows)
arena_x, arena_y = list(range(cols)), list(range(rows))
arena_xv, arena_yv = np.meshgrid(arena_x,arena_y)
#new_arena = np.meshgrid(arena_x,arena_y)
new_arena = zip(*[arena_xv,arena_yv])
#print(list(new_arena))
print(arena_xv)
print(arena_yv)

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]


In [40]:
b = np.arange(4).reshape(2,2)
print(b)
a = np.ones((3,3))
a[arena_xv,arena_yv] = b[arena_xv,arena_yv]
a

[[0 1]
 [2 3]]


array([[0., 1., 1.],
       [2., 3., 1.],
       [1., 1., 1.]])

In [42]:
(1,2)[1]

2

In [47]:
r = np.subtract([2,2],[0,1])
np.add(r,[2,2])
#print(list(r))

array([4, 3])

In [49]:
2*(2,2)

(2, 2, 2, 2)

In [51]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [52]:
[1.0,2.0]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [64]:
b = np.arange(4).reshape(2,2)
print(b)
print(b[[(1,1)]])
c = [(0,0),(1,1)]
for i in range(len(c)):
    print(b[c[i]])

[[0 1]
 [2 3]]
[[2 3]
 [2 3]]
0
3


In [54]:
list([(1,15)])

[(1, 15)]

In [6]:
np.shape(np.arange(16).reshape(-1,4,4))

(1, 4, 4)

In [9]:
np.shape([np.arange(16).reshape(4,4)])

(1, 4, 4)

In [12]:
a = np.arange(16).reshape(4,4)
print(a)
print(np.shape(a.reshape(-1,4,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(1, 4, 4)


In [13]:
number_to_actions = {0:"UP", 1:"RIGHT", 2:"DOWN", 3:"LEFT", 4:"BOMB", 5:"WAIT"}
len(number_to_actions)

6

In [15]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.subtract([2,3],1)

array([1, 2])

In [19]:
int((7-1)/2)

3

In [40]:
x,y = 7,7
grid_off = 2
arena_x, arena_y = np.linspace(0,8,9,dtype=int), np.linspace(0,8,9,dtype=int)
proj = [(xi,yi) for xi in arena_x for yi in arena_y if np.any(abs(xi-x)<=grid_off) &  np.any(abs(yi-y)<=grid_off)]
print(proj)
print(len(proj))

[(5, 5), (5, 6), (5, 7), (5, 8), (6, 5), (6, 6), (6, 7), (6, 8), (7, 5), (7, 6), (7, 7), (7, 8), (8, 5), (8, 6), (8, 7), (8, 8)]
16


In [28]:
5 in arena_x

True

In [54]:
x,y = 0,0
arena_x, arena_y = np.linspace(0,6,7,dtype=int), np.linspace(0,6,7,dtype=int)
proj = [(xi,yi) for xi in arena_x for yi in arena_y if np.any(abs(xi-x)<=grid_off) &  np.any(abs(yi-y)<=grid_off)]
print(proj)
a = np.arange(16).reshape(4,4)
for (xi,yi) in proj:
    print(a[xi,yi])

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
0
1
2
4
5
6
8
9
10


In [41]:
np.subtract((4,1),(1,2))

array([ 3, -1])

In [44]:
a = np.arange(16).reshape(4,4)
a[np.array([1,2])]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])